/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#080B14",
        surface: "#080B14",
        "inverse-primary": "#795900",
        "surface-container-high": "#272a34",
        "tertiary-fixed-dim": "#aec6ff",
        "on-primary-fixed": "#261a00",
        "inverse-on-surface": "#2d303a",
        "secondary-fixed": "#c9e6ff",
        "on-tertiary": "#002e6a",
        "surface-bright": "#363943",
        "on-primary": "#402d00",
        primary: "#D4A843",
        "on-tertiary-container": "#1b407f",
        "secondary-container": "#0EA5E9",
        "on-secondary-container": "#00344e",
        "on-tertiary-fixed-variant": "#214584",
        "primary-fixed": "#ffdf9f",
        "surface-tint": "#D4A843",
        "surface-variant": "#32343f",
        "surface-container-lowest": "#080B14",
        "on-primary-container": "#553e00",
        "on-secondary-fixed-variant": "#004c6e",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#89ceff",
        secondary: "#0EA5E9",
        "surface-dim": "#080B14",
        "on-secondary-fixed": "#001e2f",
        "tertiary-container": "#8eaef4",
        "surface-container-highest": "#32343f",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#d8e2ff",
        "on-surface-variant": "#8B95B0",
        "primary-fixed-dim": "#D4A843",
        "on-surface": "#F0F4FF",
        outline: "#9a8f7d",
        "on-primary-fixed-variant": "#5b4300",
        "on-secondary": "#00344d",
        "outline-variant": "#4e4636",
        "inverse-surface": "#F0F4FF",
        "on-background": "#F0F4FF",
        "on-tertiary-fixed": "#001a42",
        "surface-container-low": "#181b25",
        "error-container": "#93000a",
        "primary-container": "#D4A843",
        "on-error": "#690005",
        tertiary: "#b3caff",
        "surface-container": "#1c1f29",
        gold: "#D4A843",
        "electric-blue": "#0EA5E9",
        white: "#F0F4FF",
        slate: "#8B95B0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "80px",
        gutter: "24px",
        "margin-mobile": "20px",
        unit: "8px",
        "section-gap": "160px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "body-md": ["Inter"],
        "mono-technical": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-caps": ["Inter"],
        "display-sm": ["Playfair Display"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-technical": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["120px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "display-sm": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
